### ISSUE TITLE
jakarta-annotations-api missing in classpath when using maven

### ISSUE THREAD

**Issue by Perdjesk** [microsoft/kiota-java#1447]
The artifacts over https://oss.sonatype.org/#nexus-search;quick~kiota have the dependency with scope `runtime`. Example https://oss.sonatype.org/service/local/repositories/releases/content/com/microsoft/kiota/microsoft-kiota-serialization-json/1.1.14/microsoft-kiota-serialization-json-1.1.14.pom 

```
<dependency>
  <groupId>jakarta.annotation</groupId>
  <artifactId>jakarta.annotation-api</artifactId>
  <version>2.1.1</version>
  <scope>runtime</scope>
</dependency>
```

The generated code includes usage of this API:
```
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
@jakarta.annotation.Generated("com.microsoft.kiota")
public class GhClient extends BaseRequestBuilder {
```

Which leads to compilation errors:

```
package jakarta.annotation does not exist
```

**Comment by baywet** [comment]
Hi @Perdjesk 
Thanks for using kiota and for bringing this up.
The reason why this dependency is a "runtime" dependency is because it's added as an implementation dependency.
https://github.com/microsoft/kiota-java/blob/6f9a3219a543fe30525931339e33bd8ad27ae2f3/components/serialization/json/gradle/dependencies.gradle#L10

And the reason why it's an implementation dependency is that when it wasn't, people were complaining about getting conflicts with the versions they have in their project when different.

kiota info -l java instructs people to add jakarta as a dependency to avoid missing the annotation definition.

Do you feel like we should change the configuration of this dependency?

[For reference, the different configurations available for java-plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)

**Comment by baywet** [comment]
Thanks for letting us know about the documentation gaps I'll work on pull requests to address those.

As for the reports of conflicting versions it was for JavaX at the time.
https://github.com/microsoftgraph/msgraph-sdk-java/issues/705

And thank you for the additional context here we might consider changing this setting again if we get additional feedback along those lines.
