### ISSUE TITLE
Query parameters are ignored when path parameters are expanded first

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#165]
The bug can be reproduced by this(failing) test:

```java
  public void ExpandQueryParametersAfterPathParams()
    {
        // Arrange as the request builders would
        final RequestInformation requestInfo = new RequestInformation();
        requestInfo.httpMethod= HttpMethod.GET;
        requestInfo.urlTemplate = "{+baseurl}/users/{id}/list{?async*,page*,size*,orderBy*,search*}";

        // Act
        requestInfo.pathParameters.put("baseurl", "http://localhost:9090");
        requestInfo.pathParameters.put("id", 1);
        requestInfo.addQueryParameter("async", true);
        requestInfo.addQueryParameter("size", 10);

        // Assert
        var uriResult = assertDoesNotThrow(() -> requestInfo.getUri());
        System.out.println(uriResult.toString());
        assertTrue(uriResult.toString().contains("size=10"));
        assertTrue(uriResult.toString().contains("async=true"));
    }
```

[`epandOnly`](https://github.com/microsoft/kiota-java/blob/a62e2917806f69e520c3df68b79957253a9e4cbd/components/abstractions/src/main/java/com/microsoft/kiota/RequestInformation.java#L67) seems to be expanding only the first match and ignoring the subsequent.

I can look, and eventually fix it, on Monday 👍 

Additional question:
[this library](https://github.com/hal4j/uritemplate) seems to be pretty much in maintenance mode, have you considered embedding the sources or switching to something else? Or do you think that is solid enough?

**Comment by baywet** [comment]
Hey @andreaTP 
Thanks for bringing this up.

I wonder what happens if you change the template to this `{+baseurl}/users/{id}/list{?async,page,size,orderBy,search}` (no explosion) ?

But yes, even without changing the template it is strange behaviour that should be fixed.

As per the library, we've been happy with it to date. We're not expecting a ton of updates once the RFC 6570 is fully implemented, and we only need the expansion to be implemented to level 4, we don't need more advanced features like extracting parameters values from an already expanded URI. But if you can suggest a better alternative, we'll be happy to swap (request information should pretty much be the only place to update).

Happy to merge your PR when you have time to tackle this one!
