### ISSUE TITLE
Avoid usage of reflection API in Enum deserialization

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#840]
https://github.com/microsoft/kiota-java/blob/033afd138a5692a7baf1f2003b4669476a5f7110/components/serialization/json/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java#L309

This is extremely unsafe and it works only because there is a "hidden" contract with the generator to emit the specific `forValue` method on the enum class.
My first reaction would be to make it more similar to a normal "class", and extend the API of `ValuedEnum` to cover the deserialization explicitly.

Please note that this is going to be a breaking API change for abstractions and I hope we can fix it before GA.

Do you have any prior art on the subject?
Any consideration?

**Comment by baywet** [comment]
Thanks for bringing this up.

The reason why we had to resolve to reflections are because it's a static method, so it can't be part of the ValuedEnum interface like [getValue](https://github.com/microsoft/kiota-java/blob/c59eb4a69bb0dfb6ad2da4f9045290d0e154f2ef/components/abstractions/src/main/java/com/microsoft/kiota/serialization/ValuedEnum.java#L6), because the return type varies (based on the enum type, but maybe we could get around that with generics). 
And this is a static method because we don't have an instance yet.

See this example
https://github.com/microsoft/kiota-samples/blob/ca6f9e6f07fc441d4be167aa55bb1afa75c1c909/msgraph-mail/java/utilities/src/main/java/graphjavav4/utilities/models/BodyType.java#L17

If you have a better solution, let me know, I agree that reflection is costly and risky.

**Comment by andreaTP** [comment]
> And this is a static method because we don't have an instance yet.

Right, but this is a design choice, we can make it a class method and have a static way of retrieving an instance ( similar to what `createFromDiscriminatorValue` does.
Alternatively, we can add an interface at the parent level, but this means that no enum can be serialized without the scope of an object which seems to be a limitation.

**Comment by baywet** [comment]
I think the first option would probably work better here. In fact [this is what we're doing in Go](https://github.com/microsoft/kiota-serialization-json-go/blob/f25b7a9dc4bc58bb907a236b4c97af25273de9ed/json_parse_node.go#L503) I think the history here was that I implemented it in dotnet, patched it in Java, later on implemented it in Go, and never went back to update java 🤦‍♂️

Is this something you want to take a look at?

**Comment by baywet** [comment]
For visibility for everyone, here are the changes we're talking about:
1. introduce an "ValuedEnumParser" interface (generic, defines a forValue method, functional)
2. make the getEnumValue, and getCollectionOfEnumValues method accept that as a second parameter
3. update the generation so it passes a lambda to the method as a second argument.
