### ISSUE TITLE
Using https:// as part of the allowedHosts shouldn't be an issue

### ISSUE THREAD

**Issue by maisarissi** [microsoft/kiota-java#939]
When using Azure Identity to create an authProvider and adding a allowedHost as the following:

```java
final String[] allowedHosts = new String[] {"https://graph.microsoft.com"};
```
makes the client creation fail with "empty token" error.

I should be able to add allowedHosts with and without https://

**Comment by andrueastman** [comment]
@baywet  Should we also move this one up to include all the other languages' `AllowedHostValidators` to try to strip out URI semantics before comparing the hosts?

**Comment by baywet** [comment]
@andrueastman since this is not impacting generation I meant to create issues in the other abstractions repos. But I had forgotten. This is now done, thanks for the nudge. This should be considered a low priority item for now, and http (without the S) should also be considered, as well as different casings.

**Comment by andrueastman** [comment]
> @andrueastman since this is not impacting generation I meant to create issues in the other abstractions repos. But I had forgotten. This is now done, thanks for the nudge. This should be considered a low priority item for now, and http (without the S) should also be considered, as well as different casings.

Thanks for confirming here

**Comment by XdpCs** [comment]
I believe there may not be a need to make changes to this issue, as it introduces potential confusion regarding the concept of hosts.

**Comment by baywet** [comment]
@XdpCs can you expand on the scenario you are thinking about please?

**Comment by XdpCs** [comment]
In my opinion, allowedHosts should only include the hosts, not the entire URLs. Including ‘http’ or ‘https’ would involve the entire URL, while hosts are just a part of the URL.

**Comment by baywet** [comment]
I understand the concern about the naming. The reason why Maisa created this issue is because we've observed it's a mistake (leave the scheme) that's commonly made and often trips people when they first try kiota.
Instead of stripping it automatically, we could throw an exception with an explicit message. What do you think about this alternative?

**Comment by XdpCs** [comment]
I appreciate the consideration of this alternative. However, if someone directly utilizes [the specified link](https://github.com/microsoft/kiota-abstractions-go/blob/6f6c124cea15fa90d1a96763fbfbc01259710bfa/authentication/allowed_hosts_validator.go#L14) in the kiota-abstractions-go repository, there might be compatibility issues. This function will add an error param for return.

**Comment by XdpCs** [comment]
If you don't think this is a problem, I will provide the Go version.
